### ISSUE TITLE
Ring uberjar

### ISSUE THREAD

**Issue by kleewho** [strongh/lein-init-script#6]
Maybe it's just my lack of knowledge but running:
```
lein uberjar
```

produces uberjar with `no main manifest attribute, in target/clogrid-0.1.0-SNAPSHOT-standalone.jar`
On the other hand 
```
lein ring uberjar
```

works just fine. Either you could enlighten me how to fix the first one or I'll propose a way to specify somehow to use `ring uberjar`. I hope that I'll just don't know what I'm doing and the latter won't be needed

**Comment by strongh** [comment]
Hello,

Yeah I'd expect `ring uberjar` to do  some additional magic. I don't think there's an existing way to do this.

The `uberjar` task is run here:

https://github.com/strongh/lein-init-script/blob/master/src/leiningen/init_script.clj#L114

I'd be happy to see a PR to support this. Maybe it would work to add a configuration option which would select the (namespaced) fn that would build the uberjar. e.g.

https://github.com/weavejester/lein-ring/blob/master/src/leiningen/ring/uberjar.clj#L23

**Comment by kleewho** [comment]
As a simple workaround. Disable somehow calling `uberjar` and instead call: 
```
lein do ring uberjar, init-script 
```

I'm not sure whether conditional disabling `uberjar` is something you could agree on. Or if it's even less work to do.

**Comment by strongh** [comment]
I'd accept a PR for an option which would disable calling uberjar, if it's useful for your use case. I forget whether `ring uberjar` produces artifacts with the same names as vanilla `uberjar`; if not, it might be necessary to have an option for the artifact name.

**Comment by kleewho** [comment]
Ok. I'll prepare one as soon as I'll find some time.

2015-02-01 18:16 GMT+01:00 Homer Strong <notifications@github.com>:
